### ISSUE TITLE
关于stopPropagation方法的说法有点错误

### ISSUE THREAD

**Issue by WuYufeng233** [huyaocode/webKnowledge#1]
MDN上关于stopPropagation方法的描述如下：The stopPropagation() method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases.应该是阻止在捕获阶段或冒泡阶段继续传播，而不是阻止冒泡。

**Comment by huyaocode** [comment]
> MDN上关于stopPropagation方法的描述如下：The stopPropagation() method of the Event interface prevents further propagation of the current event in the capturing and bubbling phases.应该是阻止在捕获阶段或冒泡阶段继续传播，而不是阻止冒泡。

非常感谢您的提醒，我们一起做好这个文档！！！已经更正了，有什么好的资料也可发给我我一并总结进去哦
